#!/usr/bin/env python3
"""
smpc_verify.py — scheduled re-verification of the source documents cited in
public/reversal.html.

For each entry in CHECKS, fetch the URL, verify the response is 2xx, and
verify that a list of landmark substrings still appears in the response body.
Landmark substrings are deliberately generic (e.g., "Ondexxya", "TA697",
"andexanet alfa") so the check stays robust across benign rewording while
still flagging if a page is removed, replaced, or radically changed.

Output: a markdown report at outputs/_smpc_verify_log.md plus an exit code
that is 0 when all checks pass and 1 when any check fails. The GitHub
Actions wrapper opens an issue when the exit code is non-zero.

This is a monitoring job, not a PR gate. It runs weekly on a schedule and
on manual dispatch. It never runs on PRs and never blocks main.

Run locally:
    python3 scripts/smpc_verify.py
"""
from __future__ import annotations

import datetime as _dt
import os
import sys
import urllib.request
import urllib.error

USER_AGENT = (
    "Mozilla/5.0 (compatible; HaemCalc-SmPC-Monitor/1.0; "
    "+https://www.haemcalc.com/) WeeklyVerify"
)
TIMEOUT_SECONDS = 30

# Each entry: (ref_id, human label, URL, list of landmark substrings to verify).
# Landmarks are intentionally short and generic so that benign rewording does
# not cause false positives. The intent is to catch removal, replacement, or
# radical change, not to enforce verbatim wording.
CHECKS = [
    (
        "nice_ta697",
        "NICE TA697 (andexanet alfa for life-threatening or uncontrolled GI bleeding)",
        "https://www.nice.org.uk/guidance/ta697",
        ["TA697", "andexanet"],
    ),
    (
        "nice_ta1029",
        "NICE TA1029 (terminated andexanet ICH appraisal)",
        "https://www.nice.org.uk/guidance/ta1029",
        ["TA1029"],
    ),
    (
        "ondexxya_smpc",
        "Ondexxya (andexanet alfa) SmPC on emc",
        "https://www.medicines.org.uk/emc/product/10933/smpc",
        ["Ondexxya", "andexanet alfa"],
    ),
    (
        "praxbind_smpc",
        "Praxbind (idarucizumab) SmPC on emc",
        "https://www.medicines.org.uk/emc/product/2837/smpc",
        ["Praxbind", "idarucizumab"],
    ),
    (
        "smc_2273",
        "SMC advice 2273 (andexanet alfa)",
        "https://www.scottishmedicines.org.uk/medicines-advice/andexanet-alfa-ondexxya-full-smc2273/",
        ["andexanet"],
    ),
    (
        "bsh_andex",
        "BSH andexanet alfa position statement",
        "https://b-s-h.org.uk/guidelines/guidelines/use-of-andexanet-alfa-a-british-society-for-haematology-position-statement",
        ["andexanet"],
    ),
    (
        "halt_it",
        "HALT-IT (tranexamic acid in GI bleeding) PubMed entry",
        "https://pubmed.ncbi.nlm.nih.gov/32563378/",
        ["HALT-IT"],
    ),
    (
        "crash2",
        "CRASH-2 (tranexamic acid in trauma) PubMed entry",
        "https://pubmed.ncbi.nlm.nih.gov/20554319/",
        ["CRASH-2"],
    ),
    (
        "crash3",
        "CRASH-3 (tranexamic acid in TBI) PubMed entry",
        "https://pubmed.ncbi.nlm.nih.gov/31623894/",
        ["CRASH-3"],
    ),
    (
        "annexa1",
        "ANNEXA-I (Connolly et al, NEJM 2024) PubMed entry",
        "https://pubmed.ncbi.nlm.nih.gov/38804514/",
        ["andexanet"],
    ),
]


def fetch(url: str) -> tuple[int, str, str | None]:
    """Return (status_code, body_text, error_message)."""
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT_SECONDS) as resp:
            status = resp.getcode()
            raw = resp.read()
            try:
                body = raw.decode("utf-8", errors="replace")
            except Exception:
                body = ""
            return status, body, None
    except urllib.error.HTTPError as e:
        return e.code, "", f"HTTPError: {e.code} {e.reason}"
    except urllib.error.URLError as e:
        return 0, "", f"URLError: {e.reason}"
    except Exception as e:
        return 0, "", f"{type(e).__name__}: {e}"


def main() -> int:
    started = _dt.datetime.now(_dt.timezone.utc)
    report_lines: list[str] = []
    report_lines.append("# SmPC and reference verification log")
    report_lines.append("")
    report_lines.append(
        f"Run start: {started.isoformat(timespec='seconds')}  "
        f"(UTC, scheduled weekly + on manual dispatch)"
    )
    report_lines.append("")
    report_lines.append(
        "This log is regenerated by `.github/workflows/smpc-verify.yml`. "
        "Each row checks that a referenced source is still reachable and still "
        "contains landmark substrings. A failure means the source page may "
        "have been moved, replaced, or radically rewritten; the clinical "
        "wording captured in `public/reversal.html` should then be re-checked "
        "against the live source by hand."
    )
    report_lines.append("")
    report_lines.append("| ref id | source | status | landmarks present | notes |")
    report_lines.append("|---|---|---|---|---|")

    failures: list[str] = []

    for ref_id, label, url, landmarks in CHECKS:
        status, body, err = fetch(url)
        if err is not None:
            report_lines.append(
                f"| `{ref_id}` | {label} | FETCH-ERROR | n/a | {err} |"
            )
            failures.append(f"{ref_id}: {err}")
            continue
        if not (200 <= status < 300):
            report_lines.append(
                f"| `{ref_id}` | {label} | HTTP {status} | n/a | non-2xx response |"
            )
            failures.append(f"{ref_id}: HTTP {status}")
            continue
        # Case-insensitive substring check on a body subset to avoid huge memory.
        body_lower = body.lower()
        missing = [lm for lm in landmarks if lm.lower() not in body_lower]
        landmark_summary = (
            "all present"
            if not missing
            else f"missing: {', '.join(missing)}"
        )
        if missing:
            report_lines.append(
                f"| `{ref_id}` | {label} | HTTP {status} | {landmark_summary} "
                f"| landmark drift; verify source by hand |"
            )
            failures.append(
                f"{ref_id}: landmarks missing {missing} on HTTP {status} response"
            )
        else:
            report_lines.append(
                f"| `{ref_id}` | {label} | HTTP {status} | {landmark_summary} | OK |"
            )

    report_lines.append("")
    if failures:
        report_lines.append(f"## Summary: {len(failures)} of {len(CHECKS)} checks failing")
        report_lines.append("")
        for f in failures:
            report_lines.append(f"- {f}")
    else:
        report_lines.append(f"## Summary: all {len(CHECKS)} checks passing")

    report_lines.append("")
    report_lines.append(
        "_This is a monitoring job. It does not block main and never runs on PRs._"
    )
    report_lines.append("")

    out_dir = os.environ.get("SMPC_VERIFY_OUT_DIR", "outputs")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "_smpc_verify_log.md")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(report_lines) + "\n")

    print("Wrote report to", out_path)
    print("Checks total:", len(CHECKS), "failures:", len(failures))

    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
